# -*- restclient -*-
# 
# REST client for Emacs:
# https://github.com/pashky/restclient.el

# Ex. 3.4: Delete an existing entry

DELETE http://localhost:3001/api/persons/2

# Ex. 3.4: Delete a non-existent entry

DELETE http://localhost:3001/api/persons/100

# Ex. 3.5: Post a new entry

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Abraham Lincoln",
    "number": "12345-67890"
}

# Ex. 3.6: Post an entry with 'name' missing

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "12345-67890"
}

# Ex. 3.6: Post an entry with 'number' missing

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Abraham Lincoln"
}

# Ex. 3.17: Put a new number for an existing person

PUT http://localhost:3001/api/persons/66ab7b89dcc1e8f32af3bd5d
Content-Type: application/json

{
    "name": "Frontend Person",
    "number": "999-999-999"
}