# -*- restclient -*-
# 
# REST client for Emacs:
# https://github.com/pashky/restclient.el

# Ex. 3.4: Delete an existing entry

DELETE http://localhost:3001/api/persons/2

# Ex. 3.4: Delete a non-existent entry

DELETE http://localhost:3001/api/persons/100
